services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-tensorflow-nvidia-jupyter:2.15.0
    container_name: tensorflow-nvidia
    ports:
      - "8888:8888"
    runtime: nvidia